name: mediguard-clinic

include:
  - ./postgres/docker-compose.yml
  - ./kong/docker-compose.yml

services:
  kong:
    depends_on:
      kong-migrations:
        condition: service_completed_successfully

  kong-migrations:
    depends_on:
      postgres_db:
        condition: service_healthy