name: mediguard-clinic

include:
  - ./postgres/docker-compose.yml
  - ./kong/docker-compose.yml
  - ./kafka/docker-compose.yml
  - ./redis/docker-compose.yml
  - ./auth/docker-compose.yml
  - ./consumer_db/docker-compose.yml
  - ./consumer_analysis/docker-compose.yml
  - ./biosignal/docker-compose.yml