"""empty message

Revision ID: 03d52e40523e
Revises: b20736c411c3
Create Date: 2026-04-13 13:41:54.228912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03d52e40523e'
down_revision: Union[str, Sequence[str], None] = 'b20736c411c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('patient_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_number', sa.String(length=255), nullable=False),
    sa.Column('patient_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_patient_patient_id'), 'patient', ['patient_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_patient_patient_number'), 'patient', ['patient_number'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_patient_patient_number'), table_name='patient', schema='auth')
    op.drop_index(op.f('ix_auth_patient_patient_id'), table_name='patient', schema='auth')
    op.drop_table('patient', schema='auth')
    # ### end Alembic commands ###
