"""Initial migration

Revision ID: b20736c411c3
Revises: 
Create Date: 2026-03-26 14:59:55.738691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20736c411c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('permissions', sa.Enum('administrator', 'practitioner', name='authpermissionenum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_user_id'), 'users', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=True, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_user_id'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
