"""empty message

Revision ID: 1075867e6c58
Revises: ce6ef08136fa
Create Date: 2026-05-18 14:35:57.385313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1075867e6c58'
down_revision: Union[str, Sequence[str], None] = 'ce6ef08136fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bp_measure_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('base_sbp', sa.Float(), nullable=False),
    sa.Column('base_dbp', sa.Float(), nullable=False),
    sa.Column('predicted_sbp', sa.Float(), nullable=False),
    sa.Column('predicted_dbp', sa.Float(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id'),
    schema='biosignal'
    )
    op.create_index(op.f('ix_biosignal_bp_measure_log_patient_id'), 'bp_measure_log', ['patient_id'], unique=False, schema='biosignal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biosignal_bp_measure_log_patient_id'), table_name='bp_measure_log', schema='biosignal')
    op.drop_table('bp_measure_log', schema='biosignal')
    # ### end Alembic commands ###
