"""empty message

Revision ID: 3c3396264e68
Revises: 70a399aab85c
Create Date: 2026-05-11 16:45:27.741380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3396264e68'
down_revision: Union[str, Sequence[str], None] = '70a399aab85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bp_init_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('pttf', sa.Float(), nullable=False),
    sa.Column('pttd', sa.Float(), nullable=False),
    sa.Column('dPtt', sa.Float(), nullable=False),
    sa.Column('dPttNorm', sa.Float(), nullable=False),
    sa.Column('upSlope', sa.Float(), nullable=False),
    sa.Column('pw50', sa.Float(), nullable=False),
    sa.Column('diaSlope', sa.Float(), nullable=False),
    sa.Column('auc', sa.Float(), nullable=False),
    sa.Column('acdc', sa.Float(), nullable=False),
    sa.Column('rrMean', sa.Float(), nullable=False),
    sa.Column('rrStd', sa.Float(), nullable=False),
    sa.Column('baseSBP', sa.Float(), nullable=False),
    sa.Column('baseDBP', sa.Float(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id'),
    schema='biosignal'
    )
    op.create_index(op.f('ix_biosignal_bp_init_log_patient_id'), 'bp_init_log', ['patient_id'], unique=False, schema='biosignal')
    op.drop_index(op.f('biosignal_metrics_created_at_idx'), table_name='biosignal_metrics', schema='biosignal')
    op.drop_index(op.f('biosignals_recorded_at_idx'), table_name='biosignals', schema='biosignal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('biosignals_recorded_at_idx'), 'biosignals', [sa.literal_column('recorded_at DESC')], unique=False, schema='biosignal')
    op.create_index(op.f('biosignal_metrics_created_at_idx'), 'biosignal_metrics', [sa.literal_column('created_at DESC')], unique=False, schema='biosignal')
    op.drop_index(op.f('ix_biosignal_bp_init_log_patient_id'), table_name='bp_init_log', schema='biosignal')
    op.drop_table('bp_init_log', schema='biosignal')
    # ### end Alembic commands ###
