"""empty message

Revision ID: 647f36695c66
Revises: 1075867e6c58
Create Date: 2026-05-19 01:29:39.773618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647f36695c66'
down_revision: Union[str, Sequence[str], None] = '1075867e6c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bio_metrics',
    sa.Column('matrix_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('hr', sa.Float(), nullable=False),
    sa.Column('rr', sa.Float(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=False),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('matrix_id', 'recorded_at'),
    schema='biosignal'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bio_metrics', schema='biosignal')
    # ### end Alembic commands ###
