"""empty message

Revision ID: 70a399aab85c
Revises: 
Create Date: 2026-04-23 12:28:51.101964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a399aab85c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biosignal_metrics',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('matric_type', sa.Enum('BPM', 'BP', 'HR', 'RR', 'TEMP', 'SPO2', name='matrictypeenum'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('patient_id', 'matric_type', 'created_at'),
    schema='biosignal'
    )
    op.create_table('biosignals',
    sa.Column('biosignal_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('biosignal_data', sa.LargeBinary(), nullable=False),
    sa.Column('biosignal_type', sa.Enum('ECG', 'PPG', 'RESP', name='biosignaltypeenum'), nullable=False),
    sa.Column('recorded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('biosignal_id', 'recorded_at'),
    schema='biosignal'
    )
    op.create_index(op.f('ix_biosignal_biosignals_patient_id'), 'biosignals', ['patient_id'], unique=False, schema='biosignal')
    op.execute(
        "SELECT create_hypertable('biosignal.biosignal_metrics', 'created_at', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE)")
    op.execute(
        "SELECT create_hypertable('biosignal.biosignals', 'recorded_at', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_biosignal_biosignals_patient_id'), table_name='biosignals', schema='biosignal')
    op.drop_table('biosignals', schema='biosignal')
    op.drop_table('biosignal_metrics', schema='biosignal')
    # ### end Alembic commands ###
