services:
  kong-migrations:
    image: kong:3.9
    container_name: kong-migrations
    command: kong migrations bootstrap
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy

  kong:
    image: kong:3.9
    container_name: kong-gateway
    restart: always
    env_file:
      - .env
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    ports:
      - "10080:8000"     # API Proxy Port
      - "18443:8443"   # SSL Proxy Port
      - "18001:8001"   # Admin API Port
      - "18002:8002"   # Kong Manager (GUI) Port