"""Initial migration

Revision ID: 4007e255839d
Revises: 
Create Date: 2026-03-26 15:00:26.999215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4007e255839d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward',
    sa.Column('ward_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ward_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ward_id'),
    schema='clinical_manage'
    )
    op.create_index(op.f('ix_clinical_manage_ward_ward_id'), 'ward', ['ward_id'], unique=False, schema='clinical_manage')
    op.create_index(op.f('ix_clinical_manage_ward_ward_name'), 'ward', ['ward_name'], unique=True, schema='clinical_manage')
    op.create_table('patient',
    sa.Column('patient_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_number', sa.String(length=255), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('sex', sa.Enum('M', 'F', 'U', name='genderenum'), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('is_admitted', sa.Boolean(), nullable=False),
    sa.Column('admitted_ward_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('discharged_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admitted_ward_id'], ['clinical_manage.ward.ward_id'], ),
    sa.PrimaryKeyConstraint('patient_id'),
    schema='clinical_manage'
    )
    op.create_index(op.f('ix_clinical_manage_patient_patient_id'), 'patient', ['patient_id'], unique=False, schema='clinical_manage')
    op.create_index(op.f('ix_clinical_manage_patient_patient_number'), 'patient', ['patient_number'], unique=True, schema='clinical_manage')
    op.create_table('manage',
    sa.Column('manage_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['clinical_manage.patient.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manage_id'),
    sa.UniqueConstraint('patient_id'),
    schema='clinical_manage'
    )
    op.create_index(op.f('ix_clinical_manage_manage_manage_id'), 'manage', ['manage_id'], unique=False, schema='clinical_manage')
    op.create_index(op.f('ix_clinical_manage_manage_practitioner_id'), 'manage', ['practitioner_id'], unique=False, schema='clinical_manage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_manage_manage_practitioner_id'), table_name='manage', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_manage_manage_id'), table_name='manage', schema='clinical_manage')
    op.drop_table('manage', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_patient_patient_number'), table_name='patient', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_patient_patient_id'), table_name='patient', schema='clinical_manage')
    op.drop_table('patient', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_ward_ward_name'), table_name='ward', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_ward_ward_id'), table_name='ward', schema='clinical_manage')
    op.drop_table('ward', schema='clinical_manage')
    # ### end Alembic commands ###
