"""empty message

Revision ID: 403299884fda
Revises: 
Create Date: 2026-04-20 15:43:07.772146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403299884fda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('department_name', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('department_id'),
    schema='clinical_manage'
    )
    op.create_index(op.f('ix_clinical_manage_department_department_id'), 'department', ['department_id'], unique=False, schema='clinical_manage')
    op.create_index(op.f('ix_clinical_manage_department_department_name'), 'department', ['department_name'], unique=True, schema='clinical_manage')
    op.create_table('practitioner_profiles',
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('rule', sa.Enum('UNSPECIFIED', 'GP', 'SPECIALIST', 'RN', 'NP', 'OTHER', name='practitionerroleenum'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('practitioner_id'),
    schema='clinical_manage'
    )
    op.create_index(op.f('ix_clinical_manage_practitioner_profiles_practitioner_id'), 'practitioner_profiles', ['practitioner_id'], unique=False, schema='clinical_manage')
    op.create_table('ward',
    sa.Column('ward_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ward_name', sa.String(length=255), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ward_id'),
    schema='clinical_manage'
    )
    op.create_index(op.f('ix_clinical_manage_ward_ward_id'), 'ward', ['ward_id'], unique=False, schema='clinical_manage')
    op.create_index(op.f('ix_clinical_manage_ward_ward_name'), 'ward', ['ward_name'], unique=True, schema='clinical_manage')
    op.create_table('patient_profile',
    sa.Column('patient_profile_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Enum('M', 'F', 'U', name='genderenum'), nullable=False),
    sa.Column('birth', sa.String(length=255), nullable=False),
    sa.Column('is_admitted', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('admitted_ward_id', sa.UUID(), nullable=True),
    sa.Column('manage_practitioner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('discharged_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['admitted_ward_id'], ['clinical_manage.ward.ward_id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['clinical_manage.department.department_id'], ),
    sa.ForeignKeyConstraint(['manage_practitioner_id'], ['clinical_manage.practitioner_profiles.practitioner_id'], ),
    sa.PrimaryKeyConstraint('patient_profile_id'),
    sa.UniqueConstraint('patient_id'),
    schema='clinical_manage'
    )
    op.create_index(op.f('ix_clinical_manage_patient_profile_patient_profile_id'), 'patient_profile', ['patient_profile_id'], unique=False, schema='clinical_manage')
    op.create_table('manage',
    sa.Column('manage_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('practitioner_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['clinical_manage.patient_profile.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('manage_id'),
    sa.UniqueConstraint('patient_id'),
    schema='clinical_manage'
    )
    op.create_index(op.f('ix_clinical_manage_manage_manage_id'), 'manage', ['manage_id'], unique=False, schema='clinical_manage')
    op.create_index(op.f('ix_clinical_manage_manage_practitioner_id'), 'manage', ['practitioner_id'], unique=False, schema='clinical_manage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_manage_manage_practitioner_id'), table_name='manage', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_manage_manage_id'), table_name='manage', schema='clinical_manage')
    op.drop_table('manage', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_patient_profile_patient_profile_id'), table_name='patient_profile', schema='clinical_manage')
    op.drop_table('patient_profile', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_ward_ward_name'), table_name='ward', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_ward_ward_id'), table_name='ward', schema='clinical_manage')
    op.drop_table('ward', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_practitioner_profiles_practitioner_id'), table_name='practitioner_profiles', schema='clinical_manage')
    op.drop_table('practitioner_profiles', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_department_department_name'), table_name='department', schema='clinical_manage')
    op.drop_index(op.f('ix_clinical_manage_department_department_id'), table_name='department', schema='clinical_manage')
    op.drop_table('department', schema='clinical_manage')
    # ### end Alembic commands ###
